version: '2'

services:
 first-app-service:
   build: ./first_app
   ports:
     - "3010:3000"
   volumes:
     - ./first_app:/code
     - /code/node_modules
   environment:
     NODE_ENV: 'development'
   command: yarn run dev

 second-app-service:
   build: ./second_app
   ports:
     - "3020:3000"
   volumes:
     - ./second_app:/code
     - /code/node_modules
   environment:
     NODE_ENV: 'development'
   command: yarn run dev
   depends_on:
     - first-app-service

