apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: first-app
    spec:
      containers:
      - name: first-app
        image: gcr.io/PROJECT_ID/first_app:v1
        args: 
        - /bin/sh
        - -c
        - touch /code/healthy; yarn run start
        livenessProbe:
          exec:
            command:
            - cat
            - /code/healthy
          initialDelaySeconds: 5
          periodSeconds: 15
