apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: first-app
    spec:
      containers:
      - name: first-app
        image: gcr.io/PROJECT_ID/first_app:v0
