apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: first-app-scaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: first-app-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
