apiVersion: v1
kind: Service
metadata:
  name: first-app-service
  labels:
    run: first-app-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    run: first-app
  type: ClusterIP
